import { Sign } from '@/components/documentation/sign';

export default function DocumentationFooter() {
    return (
        <footer className="border-t">
            <div className="container mx-auto flex flex-col gap-4 px-4 py-6 md:flex-row md:items-center md:justify-between">
                <div className="text-sm text-muted-foreground">
                    Documentation automatically generated by
                    OiLaravelDocumentation.
                </div>
                <div className="inline-flex items-center gap-2 text-sm text-muted-foreground">
                    Design by{' '}
                    <a
                        href="https://www.olacombe.com"
                        target="_blank"
                        className="text-foreground"
                    >
                        <Sign />
                    </a>
                </div>
            </div>
        </footer>
    );
}
